"""
augmentation/templates.py
All SystemVerilog / Verilog template functions.
generator.py calls these — no logic here, just string assembly.

Fixes applied
-------------
1. interface_block  — clk not redeclared inside body; all port widths carried correctly
2. interface_instantiation — new helper; used by generator to add `dut_if` instance
3. clock_driver     — declares `reg clk` inside the module (was undeclared)
4. dut_instantiation — clk connected directly, not via dut_if (clk drives the interface)
5. type_a_constraint — replaced class-only constraint block with $urandom_range() initial
6. run_block        — accepts named task calls per B-condition instead of wildcard placeholders
"""

from typing import Dict, List, Optional, Any


# ── File header ───────────────────────────────────────────────────────────────

def file_header(project: str, timestamp: str, top_module: str) -> str:
    return f"""\
// ============================================================================
// Auto-generated Augmented Testbench
// Project   : {project}
// Generated : {timestamp}
// Top module: {top_module}
//
// IMPORTANT: This file is auto-generated by the RTL-Analyser augmentation
// engine.  Review Type-C force/release stubs before running — they may need
// manual refinement for protocol-level correctness.
// ============================================================================
`timescale 1ns/1ps
"""


# ── Interface block ───────────────────────────────────────────────────────────

def interface_block(top_module: str, ports: Dict[str, str],
                    widths: Dict[str, Optional[str]],
                    clk_name: str = "clk") -> str:
    """
    Generate a SystemVerilog interface for DUT connection.
    clk is accepted as a module parameter — NOT redeclared inside the body.
    All ports carry their correct bus widths from port_widths.
    """
    lines = [f"interface {top_module}_if(input logic {clk_name});"]
    for name, direction in ports.items():
        if name == clk_name:
            continue                       # comes from parameter — skip
        w = widths.get(name)
        bus = f"{w} " if w else ""
        lines.append(f"    logic {bus}{name};")
    lines.append(f"endinterface : {top_module}_if\n")
    return "\n".join(lines)


def interface_instantiation(top_module: str, clk_name: str = "clk") -> str:
    """Instantiate the generated interface inside the testbench module."""
    return f"    {top_module}_if dut_if({clk_name});\n"


# ── DUT instantiation ─────────────────────────────────────────────────────────

def dut_instantiation(top_module: str, ports: Dict[str, str],
                      clk_name: str = "clk") -> str:
    """
    Connect DUT ports.
    clk comes from the testbench reg (not dut_if) because it also drives the interface.
    All other ports go through dut_if.
    """
    connections = []
    for name in ports:
        if name == clk_name:
            connections.append(f"        .{name}({name})")
        else:
            connections.append(f"        .{name}(dut_if.{name})")
    port_block = ",\n".join(connections)
    return f"""\
    // DUT instantiation
    {top_module} dut (
{port_block}
    );
"""


# ── Clock driver ──────────────────────────────────────────────────────────────

def clock_driver(clock_name: str, half_period_ns: int = 5) -> str:
    return f"""\
    // Clock — {half_period_ns * 2}ns period
    reg {clock_name};
    initial {clock_name} = 0;
    always #({half_period_ns}) {clock_name} = ~{clock_name};
"""


# ── Reset driver ──────────────────────────────────────────────────────────────

def reset_driver(reset_name: str, active_low: bool,
                 stabilise_cycles: int = 50) -> str:
    assert_val  = "0" if active_low else "1"
    release_val = "1" if active_low else "0"
    return f"""\
    // Reset driver — {stabilise_cycles}-cycle stabilisation window
    initial begin
        dut_if.{reset_name} = {assert_val};
        repeat({stabilise_cycles}) @(posedge clk);
        dut_if.{reset_name} = {release_val};
        @(posedge clk);
    end
"""


# ── Type A — weighted random stimulus ────────────────────────────────────────
# Note: SV `constraint` is a class construct (UVM sequence items).
# For a plain module-level testbench we use an initial block that
# randomises the signal with a weighted $urandom call each clock cycle.

def type_a_constraint(condition_id: str, signal_name: str,
                      bias_weight: int = 80) -> str:
    """
    Bias signal_name toward 1 on every clock edge.
    bias_weight (0-100): probability of driving 1 each cycle.
    """
    return f"""\
    // [{condition_id}] Type A — weighted random driver for '{signal_name}'
    // Biased {bias_weight}% toward 1 to exercise the enable condition.
    initial begin : rand_{condition_id}_{signal_name}
        forever begin
            @(posedge clk);
            dut_if.{signal_name} <= ($urandom_range(99, 0) < {bias_weight}) ? 1 : 0;
        end
    end
"""


# ── Type B — directed warm-up task ───────────────────────────────────────────

def type_b_warmup_task(condition_id: str, signal_name: str,
                        driver_signal: str, depth: int) -> str:
    return f"""\
    // [{condition_id}] Type B — warm-up task: drive {driver_signal} for {depth} cycles
    // to seed register '{signal_name}' toward the enable condition's target value.
    // Heuristic depth = {depth} cycles (reg_width × 2). Confirm via FSDB after first run.
    task automatic warmup_{condition_id}_{signal_name}();
        integer _i;
        for (_i = 0; _i < {depth}; _i = _i + 1) begin
            @(posedge clk);
            dut_if.{driver_signal} = 1;   // TODO: adjust to the actual upstream input
        end
        @(posedge clk);
        dut_if.{driver_signal} = 0;
    endtask
"""


# ── Type B — FSM directed sequence ───────────────────────────────────────────

def type_b_fsm_sequence(condition_id: str, fsm_reg: str,
                         target_state: str,
                         transitions: List[Dict],
                         input_signals: List[str]) -> str:
    """
    Emit a task that walks the FSM toward target_state.
    input_signals: primary-input fan-in signals for this condition (used as TODO hints).
    """
    hint = f"dut_if.{input_signals[0]}" if input_signals else "/* input signal */"

    if not transitions:
        return f"""\
    // [{condition_id}] Type B FSM — walk '{fsm_reg}' to state {target_state}
    // TODO: fill in the sequence once the FSM transition diagram is confirmed.
    task automatic go_to_{condition_id}_{target_state}();
        // Drive inputs to walk {fsm_reg} into {target_state}
        // Hint: try asserting {hint}
        @(posedge clk);
    endtask
"""

    steps = []
    for t in transitions:
        if t.get("to") == target_state:
            cond_str = t.get("condition", "?")
            steps.append(
                f"        // Transition: {t.get('from','?')} -> {target_state}\n"
                f"        // Required:   {cond_str}\n"
                f"        // TODO: drive inputs so the above condition holds, then:\n"
                f"        @(posedge clk);"
            )
    body = "\n".join(steps) if steps else f"        @(posedge clk);   // TODO"

    return f"""\
    // [{condition_id}] Type B FSM — directed sequence to reach {target_state}
    task automatic go_to_{condition_id}_{target_state}();
{body}
    endtask
"""


# ── Type C — bounded force/release stub ──────────────────────────────────────

def type_c_force_stub(condition_id: str, signal_path: str,
                       force_value: str = "1", hold_cycles: int = 8) -> str:
    safe_name = signal_path.replace(".", "_")
    return f"""\
    // [{condition_id}] Type C — bounded force/release for '{signal_path}'
    // REVIEW: confirm force value and hold duration before running.
    // Upstream logic resumes driving after release — no permanent override.
    task automatic force_{condition_id}_{safe_name}();
        force dut.{signal_path} = {force_value};
        repeat({hold_cycles}) @(posedge clk);
        release dut.{signal_path};
        @(posedge clk);
    endtask
"""


# ── FSDB dump block ───────────────────────────────────────────────────────────

def fsdb_dump_block(top_module: str) -> str:
    return f"""\
    // FSDB waveform dump — Verdi activity analysis
    initial begin
        $fsdbDumpfile("{top_module}_augmented.fsdb");
        $fsdbDumpvars(0, dut);
        $fsdbDumpMDA();
    end
"""


# ── Top-level testbench module wrapper ────────────────────────────────────────

def tb_module_wrapper(top_module: str, body: str) -> str:
    return f"""\
module tb_{top_module};

{body}
endmodule : tb_{top_module}
"""


# ── Run block skeleton ────────────────────────────────────────────────────────

def run_block(type_a_count: int,
              type_b_calls: List[str],
              type_c_calls: List[str]) -> str:
    """
    type_b_calls : list of fully-formed task call strings e.g. 'go_to_COND_002_RUN()'
    type_c_calls : list of fully-formed task call strings e.g. 'force_COND_010_sub_sig()'
    """
    b_block = "\n".join(f"        {call};" for call in type_b_calls) \
              if type_b_calls else "        // (no Type B conditions)"
    c_block = "\n".join(f"        {call};" for call in type_c_calls) \
              if type_c_calls else "        // (no Type C conditions)"

    return f"""\
    // ── Main stimulus run block ──────────────────────────────────────────────
    initial begin
        // Wait for reset deassertion
        @(posedge clk); @(posedge clk);

        // Type B warm-up sequences — seed FSM states / registers
{b_block}

        // Type C force stubs — exercise complex / cross-module enables
{c_block}

        // Randomised window — {type_a_count} Type A condition(s) driven by
        // concurrent initial blocks above; let them run for 2000 cycles.
        repeat(2000) @(posedge clk);

        $finish;
    end
"""